server:
  port: 8082

spring:
  banner:
    location: "classpath:/banner/banner.txt"
  application:
    name: cards
  profiles:
    active: "prod"
  datasource:
    url: jdbc:h2:mem:cards
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  config:
    import: "optional:configserver:http://localhost:8071"
  rabbitmq:
    host: localhost
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
#  config:
#    import:
#      - "application_qa.yml"
#      - "application_prod.yml"
#  profiles:
#    active:
#      - "qa"

#build:
#  version: "3.0"
#
#cards:
#  message: "Welcome to Simple Bank cards APIs"
#  contactDetails:
#    name: "Mohamed Hassan - Developer"
#    email: "Mohamed.Hassan@simplebank.com"
#  socialMedias:
#    - "twitter(@simplebank) -> https://twitter.com/simplebank"
#    - "facebook(simplebank) -> https://facebook.com/simplebank"
#    - "linkedin(simplebank) -> https://linkedin.com/company/simplebank"
