spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

cards:
  message: "Welcome to Simple Bank cards related Prod APIs"
  contactDetails:
    name: "Robert Carlos - Production Owner"
    email: "Robert.Carlos@simplebank.com"