services:
  rabbitmq:
    container_name: "rabbitmq"
    image: "rabbitmq:4.0-management"
    hostname: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    container_name: "configserver-ms"
    image: "codespresso/configserver:latest"
    ports:
      - "8071:8071"
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent http://localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    container_name: "accounts-ms"
    image: "codespresso/accounts:latest"
    ports:
      - "8081:8081"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    container_name: "cards-ms"
    image: "codespresso/cards:latest"
    ports:
      - "8082:8082"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    container_name: "loans-ms"
    image: "codespresso/loans:latest"
    ports:
      - "8083:8083"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  simplebank:
    driver: "bridge"