spring:
  banner:
    location: "classpath:/banner/banner.txt"
  application:
    name: "config-server"
  profiles:
    active: git
#    active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/CodeSpresso-dev/SimpleBank-config.git"
          searchPaths: "config"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
#        native:
#          search-locations: "classpath:/config"
  rabbitmq:
    host: localhost
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 8071

encrypt:
  key: "12345678901234567890123456789012"


